# Generated by Django 5.1.4 on 2025-01-25 21:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="publication",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="publication",
            name="sentiment",
            field=models.CharField(default="neutral", max_length=10),
        ),
    ]
